### ISSUE TITLE
Installation documentation incomplete

### ISSUE THREAD

**Issue by graber-1** [droptica/droopler_project#11]
`gulp compile` preceeded with install commands needs to be executed also in \web\profiles\contrib\droopler\themes\custom\droopler_theme\ folder

**Comment by grzegorz-pietrzak-droptica** [comment]
Hello,

Compiling gulp in base theme is not necessary, it makes sense only if you want tu use base CSS and overwrite it with your own stylesheets without using SCSS at all.

**Comment by graber-1** [comment]
What about /profiles/contrib/droopler/themes/custom/droopler_theme/js/min/global.min.js? It may also be that the file wasn't copied to the server for some reason but I believe it was missing before the install in the parent theme.

**Comment by grzegorz-pietrzak-droptica** [comment]
This one is also handled by gulp compile in subtheme.

**Comment by graber-1** [comment]
Then it wasn't compiled in my case for some reason.

**Comment by graber-1** [comment]
Ok, thanks!
