### ISSUE TITLE
Composer 2 Compatibility

### ISSUE THREAD

**Issue by jorap** [droptica/droopler_project#112]
Hi,

I tried to use Composer 2 to update my Droopler.
I am encountering the issues stated below.

Thanks in advance.

composer update --dry-run

The "oomphinc/composer-installers-extender" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - oomphinc/composer-installers-extender[v1.1, ..., v1.1.2] require composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - Root composer.json requires oomphinc/composer-installers-extender ^1.1 -> satisfiable by oomphinc/composer-installers-extender[v1.1, v1.1.1, v1.1.2].

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.

**Comment by grzegorz-pietrzak-droptica** [comment]
Hello, The upcoming 2.2 release is compatible with Composer 2.0.
Here's the list of changes https://github.com/droptica/droopler_project/compare/master...develop

**Comment by grzegorz-pietrzak-droptica** [comment]
Closing, as we are already fully 2.0 compatible :-)
