### ISSUE TITLE
Install instructions don't work

### ISSUE THREAD

**Issue by fwells11** [droptica/droopler_project#120]
Using the instructions from [here](https://www.droptica.com/droopler/installation/) on a vanilla ubuntu 20.10 server.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - drupal/simple_sitemap[dev-3.x, 3.3.0, ..., 3.10.0] require ext-xmlwriter * -> it is missing from your system. Install or enable PHP's xmlwriter extension.
    - droptica/droopler 8.2.2 requires drupal/simple_sitemap ^3.3 -> satisfiable by drupal/simple_sitemap[3.3.0, ..., 3.x-dev (alias of dev-3.x)].
    - drupal/simple_sitemap 3.x-dev is an alias of drupal/simple_sitemap dev-3.x and thus requires it to be installed too.
    - Root composer.json requires droptica/droopler 8.2.2 -> satisfiable by droptica/droopler[8.2.2].

Please fix the instructions or note any prereqs

**Comment by grzegorz-pietrzak-droptica** [comment]
Hello, please note you don't have `ext-xmlwriter` extension in your PHP. You may ignore it by adding the `--ignore-platform-reqs` flag to composer (not recommended).
