### ISSUE TITLE
Navigating to core/install.php throws up an error

### ISSUE THREAD

**Issue by kistulu** [droptica/droopler_project#126]
Hello,
I follow the install instructions in the repo.. Moved the compiled files to /var/www/drupal/profiles/contrib/droopler/
Navigating to  localhost it throws this error:
```
#Additional uncaught exception thrown while handling exception.
##Original

Drupal\Core\Extension\InfoParserException: The 'core_version_requirement' key must be present in profiles/contrib/droopler/core/profiles/demo_umami/demo_umami.info.yml in Drupal\Core\Extension\InfoParserDynamic->parse() (line 73 of /var/www/drupal/core/lib/Drupal/Core/Extension/InfoParserDynamic.php).

Drupal\Core\Extension\InfoParserDynamic->parse('profiles/contrib/droopler/core/profiles/demo_umami/demo_umami.info.yml') (Line: 22)
Drupal\Core\Extension\InfoParser->parse('profiles/contrib/droopler/core/profiles/demo_umami/demo_umami.info.yml') (Line: 1118)
install_profile_info('demo_umami') (Line: 1290)
_install_select_profile(Array) (Line: 456)
install_begin_request(Object, Array) (Line: 115)
install_drupal(Object) (Line: 48)

##Additional

Drupal\Core\Extension\InfoParserException: The 'core_version_requirement' key must be present in profiles/contrib/droopler/core/themes/bartik/bartik.info.yml in Drupal\Core\Extension\InfoParserDynamic->parse() (line 73 of /var/www/drupal/core/lib/Drupal/Core/Extension/InfoParserDynamic.php).

Drupal\Core\Extension\InfoParserDynamic->parse('profiles/contrib/droopler/core/themes/bartik/bartik.info.yml') (Line: 22)
Drupal\Core\Extension\InfoParser->parse('profiles/contrib/droopler/core/themes/bartik/bartik.info.yml') (Line: 554)
Drupal\Core\Extension\ExtensionList->createExtensionInfo(Object) (Line: 266)
Drupal\Core\Extension\ThemeExtensionList->createExtensionInfo(Object) (Line: 316)
Drupal\Core\Extension\ExtensionList->doList() (Line: 113)
Drupal\Core\Extension\ThemeExtensionList->doList() (Line: 282)
Drupal\Core\Extension\ExtensionList->getList() (Line: 70)
_drupal_maintenance_theme() (Line: 471)
drupal_maintenance_theme() (Line: 1019)
install_display_output(Array, Array) (Line: 271)
_drupal_log_error(Array, 1) (Line: 330)
_drupal_exception_handler(Object)

```

**Comment by grzegorz-pietrzak-droptica** [comment]
Please have a look at the path `profiles/contrib/droopler/core/profiles/demo_umami/demo_umami.info.yml` - it seems you have a complete separate Drupal instalation in the Droopler profile directory

**Comment by kistulu** [comment]
Yes that is indeed the case, should I delete the core folder there? Or what I am trying to use as a profile is meant to be used in the web root ?

**Comment by kistulu** [comment]
okay so I eventually managed to fix modules issue by copying them from /profiles/contrib/droopler/modules (since it in itself was a drupal install however won't work indepentently and give a blank install.php page) and the managed to install droopler 3.0.0 successfully
However it seems like the installer was broken or something since the website I have installed: Images don't display properly and some of the old droopler editing features like being able to just click the plus sign and adding a new component are gone.. 
If it is possibly can you please use your time to help me with how I install it properly perhaps the documentation is not complete or at best please start providing the old tarballs that you would for Drupal 8 which would work out of the box(as this has been a pain for me)

**Comment by rudy880718** [comment]
I have the same problem, the installer was broken or something since the website I have installed: Images don't display properly and some of the old droopler editing features like being able to just click the plus sign and adding a new component are gone..

**Comment by grzegorz-pietrzak-droptica** [comment]
I am closing the issue due to inactivity, please fell free to add new ones in case of problems.
