### ISSUE TITLE
Installation guide composer based leads to subtheme gulp compile errors

### ISSUE THREAD

**Issue by valica** [droptica/droopler_project#129]
How to reproduce the problem:

Follow the guide from here: https://www.droptica.com/droopler/installation/
gulp compile is failing with multiple errors and also contains some deprecation warnings.

Is it a proper way to installe Droopler in recent version?

Kind regards
Vlad VALICA

**Comment by grzegorz-pietrzak-droptica** [comment]
Hi, please paste the errors. Deprecations will be fixed in Droopler 3.1.

**Comment by valica** [comment]
Hi,
There are two problems: 
On the droptica website, at this URL: 
https://www.droptica.com/droopler/installation/

the installation steps are as following:
$ composer create-project droptica/droopler-project droopler
$ cd droopler
$ composer drupal-scaffold
$ composer install
$ cd web/themes/custom/droopler_subtheme
$ npm install
$ npm install --global gulp-cli
$ gulp compile

This leads to errors because the base theme is not compiled.

Then, if compiling the base theme and then the subtheme, there are indeed lots of warnings.
When installing the site, ther eare the following steps:

Choose language -> OK
 Verify requirements (done)
Set up database (done)
Install site (done)
Configure site (done)
Enable additional components 

Install additional components -> at this point, the following error occurs:


Installing selected components

Installation error.
Please continue to [the error page](http://localhost/droopler/core/install.php?rewrite=ok&profile=droopler&langcode=en&id=2&op=finished)

An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /droopler/core/install.php?rewrite=ok&profile=droopler&langcode=en&id=2&op=do_nojs&op=do
StatusText: OK
ResponseText: 
Deprecated:  Optional parameter $theme_name declared before required parameter $child_item is implicitly treated as a required parameter in C:\Data\webdev\drupalProjects\droopler_test\web\modules\contrib\we_megamenu\src\WeMegaMenuBuilder.php on line 549
Deprecated:  Optional parameter $theme_name declared before required parameter $child_item is implicitly treated as a required parameter in C:\Data\webdev\drupalProjects\droopler_test\web\modules\contrib\we_megamenu\src\WeMegaMenuBuilder.php on line 696
{"status":true,"percentage":"27","message":"Completed 3 of 11.","label":"Installed \u003Cem class=\u0022placeholder\u0022\u003Ed_demo\u003C\/em\u003E module."}

Do you know when Droopler 3.1 is going to be released?

Kind regards,

Vlad

**Comment by grzegorz-pietrzak-droptica** [comment]
This issue is rather dependent on the release of `we_megamenu` module. If you still get those errors then the patch didn't work.
