### ISSUE TITLE
Basic Questions

### ISSUE THREAD

**Issue by Mayakovsky** [droptica/droopler_project#132]
Need to know where I should be creating these directories.  Working out of Windows /system32 seem to be running into conflicts.

No idea what I'm doing really, just trying to get a single instance up, build a simple site, and move on to other work.

Help?  I've gotten Virtual Studios, nmp, php, latest Python.  Succeeded in creating a composer.json file, but I'd like edit access like Notepad - still trying to figure that out.  New to all this obviously.  Just need an Open Source site for a creative (me.)

Thanks

**Comment by grzegorz-pietrzak-droptica** [comment]
Hi, installing Droopler is identical to installing Drupal, please see tutorials how to run it on Windows - there are few ways to do it.

**Comment by Mayakovsky** [comment]
Yeah, thought of that. Been running through a Drupal installation since last night.  Something is preventing localhost/mydirectory from resolving completely.

https://youtu.be/SKoNC7IgJY4 is the tutorial.

![Deprecation Errors](https://user-images.githubusercontent.com/6962838/179015961-815c52ba-062e-477e-8589-91220cf48dfc.jpg)

I looked at Windows Defender/Firewall but didn't see any conflicts.  I'm assuming some needed package isn't being called at the appropriate time.

Again, it's not so much Drupal as it is I have no deep idea of how Javascript works, or if I should be loading into a new directory/folder on C drive.  Basic tutorial/FAQ space assumes a level of understanding I am missing.  Like picking up a computer and not understanding that programs are loaded into Program Files - this is the level.

any suggestions appreciated
