### ISSUE TITLE
Setting Up PATH and Directories

### ISSUE THREAD

**Issue by Mayakovsky** [droptica/droopler_project#133]
Running into major problems with Directories and PATH - could use a heads up.

Trying to load this environment onto a Windows machine using xampp virtual Apache and MySQL servers.

I'm lost on how to set up the directory hierarchy.  trying to go through htaccess due to a tutorial, but I thought this was something you had run across.

Can I build the hierarchy outside Composer environment, like Windows Explorer?

**Comment by grzegorz-pietrzak-droptica** [comment]
Hi, did you tried to follow the official manual?
https://www.drupal.org/docs/develop/local-server-setup/windows-development-environment/quick-install-drupal-with-xampp-on
