### ISSUE TITLE
Need for php 7.1?

### ISSUE THREAD

**Issue by theodorosploumis** [droptica/droopler_project#16]
Is there a need for *php 7.1*? When running ```composer install``` with php7.0 I get the error:
 
```
Problem 1
    - Installation request for doctrine/instantiator 1.1.0 -> satisfiable by doctrine/instantiator[1.1.0].
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.28) does not satisfy that requirement.
  Problem 2
    - Installation request for symfony/browser-kit v4.1.0 -> satisfiable by symfony/browser-kit[v4.1.0].
    - symfony/browser-kit v4.1.0 requires php ^7.1.3 -> your PHP version (7.0.28) does not satisfy that requirement.
  Problem 3
    - doctrine/inflector v1.3.0 requires php ^7.1 -> your PHP version (7.0.28) does not satisfy that requirement.
    - doctrine/inflector v1.3.0 requires php ^7.1 -> your PHP version (7.0.28) does not satisfy that requirement.
    - Installation request for doctrine/inflector v1.3.0 -> satisfiable by doctrine/inflector[v1.3.0].
```

**Comment by grzegorz-pietrzak-droptica** [comment]
Please try to run composer with --ignore-platform-reqs switch (I hope I did
not misspell it, just check the composer docs if it is not working).

Sob., 9 cze 2018, 11:21 użytkownik Theodoros Ploumis <
notifications@github.com> napisał:

**Comment by theodorosploumis** [comment]
Still no success. I am on Ubuntu 16.04 with php5.6.36.

**Comment by grzegorz-pietrzak-droptica** [comment]
This is very strange, after setting --ignore-platform-reqs composer does not care about php version at all, are you sure the switch is set properly?

**Comment by grzegorz-pietrzak-droptica** [comment]
Anyway, this is issue with Drupal 8, not Droopler itself - you can read more at https://www.drupal.org/project/drupal/issues/2898119. According to this page, you can force the usage of PHP 5 by adding this code to your composer.json and running composer update:

```php
"platform": {
     "php": "5.6"
 }
```
