### ISSUE TITLE
Composer Install Stumbles

### ISSUE THREAD

**Issue by atlanticdecisionsciences** [droptica/droopler_project#40]
I just tried to install droopler using composer.

Composer gives the following warning:
"droptica/droopler 8.1.3 requires bower-asset/colorbox ^1.6 -> no matching package found"

Sure enough, I don't see that asset on https://packagist.org/

**Comment by grzegorz-pietrzak-droptica** [comment]
Hello,

The asset comes from the asset-packagist.org:
https://asset-packagist.org/package/bower-asset/colorbox

Maybe they had some downtime, please try running composer again
