### ISSUE TITLE
Droopler installation process fails

### ISSUE THREAD

**Issue by partikus** [droptica/droopler_project#58]
Hi there!

I'm trying to install the project but the error is occuring.

PHP 7.2
MySQL 5.7
Droopler: 8.1.4

```bash
git clone -b develop https://github.com/droptica/droopler_project.git droopler
# the same issue occurs for official version
cd droopler/
composer install
composer drupal-scaffold
composer install
```

then in the browser I'm filling out the wizard and after submitting db credentials (some tables appeared) the following error occurs:

```
The website encountered an unexpected error. Please try again later.
Drupal\Core\Config\UnmetDependenciesException: Configuration objects provided by <em class="placeholder">droopler_subtheme</em> have unmet dependencies: <em class="placeholder">block.block.footer (block_content, block), block.block.languageswitcher (language, block), block.block.mainnavigation (block), block.block.pagetitle (ctools, block)</em> in Drupal\Core\Config\UnmetDependenciesException::create() (line 98 of core/lib/Drupal/Core/Config/UnmetDependenciesException.php).
Drupal\Core\Config\UnmetDependenciesException::create('droopler_subtheme', Array) (Line: 485)
Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall('theme', 'droopler_subtheme') (Line: 132)
Drupal\Core\ProxyClass\Config\ConfigInstaller->checkConfigurationToInstall('theme', 'droopler_subtheme') (Line: 169)
Drupal\Core\Extension\ThemeInstaller->install(Array, 1) (Line: 166)
Drupal\Core\Extension\ThemeHandler->install(Array) (Line: 1649)
install_profile_themes(Array) (Line: 709)
install_run_task(Array, Array) (Line: 584)
install_run_tasks(Array, NULL) (Line: 125)
install_drupal(Object) (Line: 44)
```

![image](https://user-images.githubusercontent.com/1732227/55615413-b0d1f380-578f-11e9-9e49-6f7ce428e792.png)

<details>
<summary>composer dependencies info</summary>
<pre>
alchemy/zippy                         0.4.3           Zippy, the archive manager companion
asm89/stack-cors                      1.2.0           Cross-origin resource sharing library and stack middleware
behat/mink                            v1.7.1          Browser controller/emulator abstraction for PHP
behat/mink-browserkit-driver          1.3.3           Symfony2 BrowserKit driver for Mink framework
behat/mink-goutte-driver              v1.2.1          Goutte driver for Mink framework
bower-asset/colorbox                  1.6.4          
bower-asset/desandro-matches-selector v2.0.2         
bower-asset/ev-emitter                v1.1.1         
bower-asset/fizzy-ui-utils            v2.0.7         
bower-asset/get-size                  v2.0.3         
bower-asset/jquery                    3.3.1          
bower-asset/lato-webfont              v1.1.2         
bower-asset/masonry                   v4.2.2         
bower-asset/outlayer                  v2.1.1         
brumann/polyfill-unserialize          v1.0.3          Backports unserialize options introduced in PHP 7.0 to older PHP versions.
composer/installers                   v1.6.0          A multi-framework Composer library installer
composer/semver                       1.5.0           Semver library that offers utilities, version constraint parsing and validation.
consolidation/annotated-command       2.12.0          Initialize Symfony Console commands from annotated command class methods.
consolidation/output-formatters       3.4.1           Format text by applying transformations provided by plug-in formatters.
cweagans/composer-patches             1.6.5           Provides a way to patch Composer packages.
dflydev/dot-access-configuration      v1.0.3          Given a deep data structure representing a configuration, access configuration by dot notation.
dflydev/dot-access-data               v1.1.0          Given a deep data structure, access data by dot notation.
dflydev/placeholder-resolver          v1.0.2          Given a data source representing key => value pairs, resolve placeholders like ${foo.bar} to the value associated with the 'foo.bar' key in the data sou...
dnoegel/php-xdg-base-dir              0.1             implementation of xdg base directory specification for php
doctrine/annotations                  v1.6.1          Docblock Annotations Parser
doctrine/cache                        v1.8.0          Caching library offering an object-oriented API for many cache backends
doctrine/collections                  v1.6.1          PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/common                       v2.10.0         PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on such as better reflection support...
doctrine/event-manager                v1.0.0          Doctrine Event Manager component
doctrine/inflector                    v1.3.0          Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                 1.2.0           A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                        v1.0.1          Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
doctrine/persistence                  v1.1.0          The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.
doctrine/reflection                   v1.0.0          Doctrine Reflection component
droptica/droopler                     8.1.4           Droopler installation profile for Drupal 8
drupal-composer/drupal-scaffold       2.6.1           Composer Plugin for updating the Drupal scaffold files when using drupal/core
drupal/admin_toolbar                  1.26.0          Provides a drop-down menu interface to the core Drupal Toolbar.
drupal/better_exposed_filters         3.0.0-alpha6    Provides advanced options (such as links, checkboxes, or jQueryUI widgets) for exposed Views elements.
drupal/checklistapi                   1.10.0          Provides an API for creating fillable, persistent checklists.
drupal/coder                          3.1.0          
drupal/colorbox                       1.4.0           A light-weight, customizable lightbox plugin for jQuery.
drupal/config_update                  1.6.0           Provides basic revert and update functionality for other modules
drupal/console                        1.8.0           The Drupal CLI. A tool to generate boilerplate code, interact with and debug Drupal.
drupal/console-core                   1.8.0           Drupal Console Core
drupal/console-en                     1.8.0           Drupal Console English Language
drupal/console-extend-plugin          0.9.2           Drupal Console Extend Plugin
drupal/contact_formatter              1.1.0           Field Formatter for Contact Forms
drupal/core                           8.6.13          Drupal is an open source content management platform powering millions of websites and applications.
drupal/ctools                         3.2.0           Provides a number of utility and helper APIs for Drupal developers and site builders.
drupal/devel                          1.2.0           Various blocks, pages, and functions for developers.
drupal/entity_reference_revisions     1.6.0           Adds a Entity Reference field type with revision support.
drupal/facets                         1.3.0           The Facet module allows site builders to easily create and manage faceted search interfaces.
drupal/features                       3.8.0           Enables administrators to package configuration into modules
drupal/field_group                    3.0.0-beta1     Provides the field_group module.
drupal/geysir                         1.1.0           Enhancing the Drupal Author Experience.
drupal/google_analytics               2.4.0           Allows your site to be tracked by Google Analytics by adding a Javascript tracking code to every page.
drupal/google_tag                     1.x-dev 7f8479a Allows your website analytics to be managed using Google Tag Manager.
drupal/link_attributes                1.6.0           Provides a widget to allow settings of link attributes for menu links.
drupal/linkit                         4.3.0           Linkit - Enriched linking experience
drupal/menu_link_attributes           1.0.0           Allows you to add attributes to menu links.
drupal/metatag                        1.8.0           Manage meta tags for all entities.
drupal/paragraphs                     1.8.0           Enables the creation of Paragraphs entities.
drupal/pathauto                       1.4.0           Provides a mechanism for modules to automatically generate aliases for the content they manage.
drupal/redirect                       1.3.0           Allows users to redirect from old URLs to new URLs.
drupal/search_api                     1.12.0          Provides a generic framework for modules offering search capabilities.
drupal/simple_sitemap                 2.12.0          Simple XML sitemap creates a standard conform XML sitemap of your content.
drupal/smtp                           1.0.0-beta4     Allow for site emails to be sent through an SMTP server of your choice.
drupal/svg_image                      1.9.0           Overrides the standard image formatter and widget to support SVG files.
drupal/token                          1.5.0           Provides a user interface for the Token API and some missing core tokens.
drupal/tvi                            1.0.0-beta2     Enables you to change the presentation of taxonomy term pages with Views, allowing you to create multiple Views on the same path with different output.
drush/drush                           8.2.3           Drush is a command line shell and scripting interface for Drupal, a veritable Swiss Army knife designed to make life easier for those of us who spend so...
easyrdf/easyrdf                       0.9.1           EasyRdf is a PHP library designed to make it easy to consume and produce RDF.
egulias/email-validator               1.2.15          A library for validating emails
fabpot/goutte                         v3.2.3          A simple PHP Web Scraper
guzzlehttp/guzzle                     6.3.3           Guzzle is a PHP HTTP client library
guzzlehttp/promises                   v1.3.1          Guzzle promises library
guzzlehttp/psr7                       1.5.2           PSR-7 message implementation that also provides common utility methods
jakub-onderka/php-console-color       v0.2           
jakub-onderka/php-console-highlighter v0.4            Highlight PHP code in terminal
jcalderonzumba/gastonjs               v1.0.3          PhantomJS API based server for webpage automation
jcalderonzumba/mink-phantomjs-driver  v0.3.3          PhantomJS driver for Mink framework
masterminds/html5                     2.6.0           An HTML5 parser and serializer.
mikey179/vfsStream                    v1.6.5          Virtual file system to mock the real file system in unit tests.
nikic/php-parser                      v4.2.1          A PHP parser written in PHP
npm-asset/almond                      0.3.3          
npm-asset/bootstrap                   4.0.0          
npm-asset/countup                     v1.9.3         
npm-asset/in-viewport                 3.6.0          
npm-asset/jquery                      3.3.1          
npm-asset/jquery-backstretch          2.1.17         
npm-asset/jquery-mousewheel           3.1.13         
npm-asset/popper.js                   1.12.3         
npm-asset/select2                     4.0.5          
npm-asset/slick-carousel              1.8.1          
oomphinc/composer-installers-extender v1.1.2          Extend the composer/installers plugin to accept any arbitrary package type.
paragonie/random_compat               v2.0.18         PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
pear/console_table                    v1.3.1          Library that makes it easy to build console style tables.
phpdocumentor/reflection-common       1.0.1           Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock     4.3.0           With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver           0.4.0          
phpspec/prophecy                      1.8.0           Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage             2.2.4           Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator             1.4.5           FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template             1.2.1           Simple template engine.
phpunit/php-timer                     1.0.9           Utility class for timing
phpunit/php-token-stream              1.4.12          Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       4.8.36          The PHP Unit Testing framework.
phpunit/phpunit-mock-objects          2.3.8           Mock Object library for PHPUnit
psr/container                         1.0.0           Common Container Interface (PHP FIG PSR-11)
psr/http-message                      1.0.1           Common interface for HTTP messages
psr/log                               1.1.0           Common interface for logging libraries
psy/psysh                             v0.9.9          An interactive shell for modern PHP.
ralouphie/getallheaders               2.0.5           A polyfill for getallheaders.
sebastian/comparator                  1.2.4           Provides the functionality to compare PHP values for equality
sebastian/diff                        1.4.3           Diff implementation
sebastian/environment                 1.3.8           Provides functionality to handle HHVM/PHP environments
sebastian/exporter                    1.2.2           Provides the functionality to export PHP variables for visualization
sebastian/global-state                1.1.1           Snapshotting of global state
sebastian/recursion-context           1.0.5           Provides functionality to recursively process PHP variables
sebastian/version                     1.0.6           Library that helps with managing the version number of Git-hosted PHP projects
stack/builder                         v1.0.5          Builder for stack middlewares based on HttpKernelInterface.
stecman/symfony-console-completion    0.9.0           Automatic BASH completion for Symfony Console Component based applications.
symfony-cmf/routing                   1.4.1           Extends the Symfony2 routing component for dynamic routes and chaining several routers
symfony/browser-kit                   v4.2.5          Symfony BrowserKit Component
symfony/class-loader                  v3.4.24         Symfony ClassLoader Component
symfony/config                        v3.4.24         Symfony Config Component
symfony/console                       v3.4.24         Symfony Console Component
symfony/css-selector                  v3.4.24         Symfony CssSelector Component
symfony/debug                         v3.4.24         Symfony Debug Component
symfony/dependency-injection          v3.4.24         Symfony DependencyInjection Component
symfony/dom-crawler                   v3.4.24         Symfony DomCrawler Component
symfony/event-dispatcher              v3.4.24         Symfony EventDispatcher Component
symfony/filesystem                    v3.4.24         Symfony Filesystem Component
symfony/finder                        v3.4.24         Symfony Finder Component
symfony/http-foundation               v3.4.24         Symfony HttpFoundation Component
symfony/http-kernel                   v3.4.24         Symfony HttpKernel Component
symfony/polyfill-ctype                v1.11.0         Symfony polyfill for ctype functions
symfony/polyfill-iconv                v1.11.0         Symfony polyfill for the Iconv extension
symfony/polyfill-mbstring             v1.11.0         Symfony polyfill for the Mbstring extension
symfony/polyfill-php70                v1.11.0         Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/process                       v3.4.24         Symfony Process Component
symfony/psr-http-message-bridge       v1.2.0          PSR HTTP message bridge
symfony/routing                       v3.4.24         Symfony Routing Component
symfony/serializer                    v3.4.24         Symfony Serializer Component
symfony/translation                   v3.4.24         Symfony Translation Component
symfony/validator                     v3.4.24         Symfony Validator Component
symfony/var-dumper                    v3.4.24         Symfony mechanism for exploring and dumping PHP variables
symfony/yaml                          v3.4.24         Symfony Yaml Component
twig/twig                             v1.38.4         Twig, the flexible, fast, and secure template language for PHP
typo3/phar-stream-wrapper             v2.1.0          Interceptors for PHP's native phar:// stream handling
webflo/drupal-finder                  1.1.0           Helper class to locate a Drupal installation from a given path.
webmozart/assert                      1.4.0           Assertions to validate method input/output with nice error messages.
webmozart/path-util                   2.3.0           A robust cross-platform utility for normalizing, comparing and modifying file paths.
zendframework/zend-diactoros          1.8.6           PSR HTTP Message implementations
zendframework/zend-escaper            2.6.0           Securely and safely escape HTML, HTML attributes, JavaScript, CSS, and URLs
zendframework/zend-feed               2.12.0          provides functionality for consuming RSS and Atom feeds
zendframework/zend-stdlib             3.2.1           SPL extensions, array utilities, error handlers, and more
</pre>
</details>

**Comment by partikus** [comment]
@grzegorzbartman @jaro2801 @MaciejLukianski 
Folks, if I'm not wrong the issue was caused by the unfinished installation. Some timeouts/limitations for fpm interpreter. 
**I would recommend to update the documenation to mention about that.** 
The process succeed when I've run installation process from CLI with `vendor/bin/drush site:install`

**Comment by grzegorz-pietrzak-droptica** [comment]
Hello, this doesn't seem to be Droopler-specific, it is rather some Composer issue.
