### ISSUE TITLE
Cannot install using composer

### ISSUE THREAD

**Issue by socialnicheguru** [droptica/droopler_project#67]
composer create-project droptica/droopler-project droopler 

  Could not find package droptica/droopler-project with stability stable.  
                                                                           

----

 composer create-project droptica/droopler-project droopler --stability dev

                                                                        
  [InvalidArgumentException]                                            
  Could not find package droptica/droopler-project with stability dev.

**Comment by michal-borek** [comment]
`composer create-project droptica/droopler-project droopler "8.2.0-beta2"` does the job :)

**Comment by rafal-sereda-droptica** [comment]
It seems like some issue withy local environment. Command <code>composer create-project droptica/droopler-project droopler</code> works as expected
