### ISSUE TITLE
SASS errors

### ISSUE THREAD

**Issue by graber-1** [droptica/droopler_project#7]
![image](https://user-images.githubusercontent.com/22659939/35267745-8edfe02c-0027-11e8-83a8-b23e6a7ca43b.png)

**Comment by graber-1** [comment]
The lines causing the error:
$d-p-banner-line-margin-top: $line-center-margin-top !default;;
$d-p-banner-line-margin-bottom: $line-center-margin-bottom !default;;

double semicolons.

**Comment by grzegorz-pietrzak-droptica** [comment]
Thanks for pointing this out, we'll fix this in next release.

**Comment by grzegorz-pietrzak-droptica** [comment]
Fixed in latest release.
