### ISSUE TITLE
config.rb for SASS compiler missing

### ISSUE THREAD

**Issue by graber-1** [droptica/droopler_project#8]
There should be a config.rb file with at least css dir defined in \web\themes\custom\droopler_subtheme\scss\

**Comment by grzegorz-pietrzak-droptica** [comment]
Hello, we use gulp to compile SCSS. So the proper way to compile stylesheets would be:

```bash
cd web/themes/custom/droopler_subtheme
npm install
npm install --global gulp-cli
gulp compile
```

**Comment by graber-1** [comment]
Ok, works fine with Gulp, thanks!
