### ISSUE TITLE
Custom blocks library errors

### ISSUE THREAD

**Issue by graber-1** [droptica/droopler_project#9]
1. In menu the custom blocks element is duplicated (same URLs)
2. When saving a custom block (footer), the values are not saved at all, no errors in logs, just a notice "content_block: updated Footer.".

![image](https://user-images.githubusercontent.com/22659939/35270625-0cbc0054-0030-11e8-8616-e84658013760.png)

**Comment by graber-1** [comment]
When I create a new block and place it in the footer main region all is fine and the block is editable.

**Comment by grzegorz-pietrzak-droptica** [comment]
Thanks, confirmed on fresh PL installation, probably the view gets duplicated in the config.

**Comment by grzegorz-pietrzak-droptica** [comment]
In 8.1.2 we fixed language issues, it should work fine now.
